---
# Relevant info: https://hashcat.net/forum/archive/index.php?thread-6063-2.html
#                http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#runfile-advanced
- name: Configure blacklist-nouveau
  become: true
  blockinfile:
    create: yes
    path: /etc/modprobe.d/blacklist-nouveau.conf
    block: |
      blacklist nouveau
      blacklist lbm-nouveau
      options nouveau modeset=0
      alias nouveau off
      alias lbm-nouveau off

- name: Configure nouveau-kms
  become: true
  blockinfile:
    create: yes
    path: /etc/modprobe.d/nouveau-kms.conf
    insertafter: EOF
    block: "options nouveau modeset=0"

- name: Update initramfs
  become: true
  command: update-initramfs -u

- name: Reboot host
  become: true  
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0

- name: Wait for reboot
  wait_for_connection:
    delay: 30
    timeout: 300

- name: Remove multiarch support
  become: true
  command: dpkg --remove-architecture i386

- name: Install Hashcat dependencies
  become: true
  when: ansible_os_family == "Debian"
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest

  with_items:
    - build-essential
    - p7zip-full
    - linux-image-extra-virtual

- name: Install Linux headers
  become: true
  shell: apt install linux-headers-$(uname -r)
  
- name: Download nVidia Drivers
  become: true
  get_url:
    url: http://us.download.nvidia.com/tesla/390.30/NVIDIA-Linux-x86_64-390.30.run
    dest: /tmp

- name: Install nVidia Drivers
  become: true
  command: /bin/bash NVIDIA-Linux-x86_64-390.30.run --silent
  args:
    chdir: /tmp

- name: Clone repository
  become: true
  git:
    repo: https://github.com/hashcat/hashcat.git
    dest: "{{ hashcat_git_location }}/hashcat"
    update: yes
    recursive: yes

- name: Build Hashcat
  become: true
  command: make
  args:
    chdir: "{{ hashcat_git_location }}/hashcat"

- name: Install Hashcat
  become: true
  command: make install
  args:
    chdir: "{{ hashcat_git_location }}/hashcat"

- name: Get card details
  command: nvidia-smi
  register: status

- name: Print results
  debug: var=status.stdout
